import {useEffect,useRef,useState} from 'react';
import Envelope from './components/Envelope';
import DateReveal from './components/DateReveal';
import PhotoCarousel from './components/PhotoCarousel';
import Postcards from './components/Postcards';
import { wedding } from './config';
const stops=['Newcastle','Davao','Tanzania','India','Hungary','London','Edinburgh','Portugal','Amsterdam','Alnwick Castle','Hong Kong'];
function Botanical(){return <svg className="botanical" viewBox="0 0 140 250" fill="none" aria-hidden="true"><path d="M70 243C90 170 48 98 83 12M76 199C30 177 21 145 27 126C58 130 76 155 76 199ZM77 166C110 152 127 125 120 104C95 107 81 130 77 166ZM72 128C40 104 37 83 43 67C69 77 71 99 72 128ZM75 80C103 71 111 46 109 33C86 37 77 56 75 80ZM79 42C64 23 67 13 76 6C87 18 88 25 79 42Z" stroke="currentColor" strokeWidth="1.2"/></svg>}
function icsText(value:string){return value.replace(/\\/g,'\\\\').replace(/;/g,'\\;').replace(/,/g,'\\,').replace(/\r?\n/g,'\\n')}
function icsTimestamp(date:Date){return date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}
function calendar(){const body=['BEGIN:VCALENDAR','VERSION:2.0','CALSCALE:GREGORIAN','METHOD:PUBLISH','PRODID:-//Rishabh and Glyra//Wedding//EN','BEGIN:VEVENT','UID:rishabh-glyra-20261021@wedding.local',`DTSTAMP:${icsTimestamp(new Date())}`,'DTSTART:20261021T023000Z',`SUMMARY:${icsText('Rishabh & Glyra · Wedding')}`,`LOCATION:${icsText(wedding.location)}`,`DESCRIPTION:${icsText('Together with their families. Reception to follow.')}`,'END:VEVENT','END:VCALENDAR',''].join('\r\n');const url=URL.createObjectURL(new Blob([body],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=wedding.calendarFileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function App(){const [opened,setOpened]=useState(false);const main=useRef<HTMLElement>(null);
 useEffect(()=>{if(!opened)return;main.current?.focus();const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[opened]);
 if(!opened)return <Envelope onOpen={()=>{setOpened(true);window.scrollTo(0,0)}}/>;
 return <><a className="skip-link" href="#main">Skip to invitation</a><header className="site-header"><a className="monogram" href="#main" aria-label="Rishabh and Glyra home">R<span>&</span>G</a><nav aria-label="Invitation"><a href="#celebrations">The celebrations</a><a href="#story">Our story</a><a href="#wishes">Send a little love <span aria-hidden="true">↗</span></a></nav><span className="header-date">21.10.26</span></header>
 <main id="main" ref={main} tabIndex={-1}><section className="hero section-pad"><div className="hero-letter"><span className="eyebrow">A love letter, to you</span><div className="little-flower" aria-hidden="true">✳</div><p className="hero-prelude">Together with our families</p><h1>Rishabh <span className="ampersand">&</span><br/><em>Glyra</em></h1><p className="hero-note">A thousand miles. A hundred goodbyes.<br/>And now, a lifetime of hellos.</p><div className="hero-date"><span>21 OCTOBER 2026</span><span>HONG KONG</span></div><a className="text-link" href="#date">Our forever starts here <span>↓</span></a></div><div className="hero-art"><div className="letter-behind"><span>WITH LOVE, ALWAYS</span><p>Officially<br/><em>boarding forever.</em></p></div><figure className="hero-photo"><img src="/images/embrace.webp" alt="Rishabh and Glyra embracing on a balcony" width="1200" height="1200" fetchPriority="high"/><figcaption>you, me & everywhere in between</figcaption></figure><div className="hero-stamp" aria-hidden="true"><span>HONG KONG</span><b>21<br/>OCT</b><span>WITH LOVE • 2026</span></div><div className="ribbon" aria-hidden="true"/><Botanical/></div><div className="hero-bottom"><span>A NEW CHAPTER, ADDRESSED TO FOREVER</span><span>SCROLL TO UNFOLD ↓</span></div></section>
 <section className="welcome section-pad reveal"><span className="eyebrow">Dear family & friends,</span><h2>Some stories are written in ink.<br/>Ours was written in <em>air miles.</em></h2><p>After years of long distance, countless flights, and more paperwork than we’d ever imagined, we’re finally getting married. And we couldn’t turn this page without you.</p><span className="handwritten">With all our love, Rishabh & Glyra</span></section>
 <DateReveal onCalendar={calendar}/><PhotoCarousel/>
 <section id="celebrations" className="celebrations section-pad reveal"><div className="section-heading"><span className="eyebrow">03 / The celebrations</span><h2>Two cities.<br/><em>One beautiful beginning.</em></h2><p>Before we fly, a celebration with our favourite people.<br/>Then, a little ceremony and a very big forever.</p></div><div className="event-grid"><article className="event"><span className="event-index">01 · THE SEND-OFF</span><h3>Davao City</h3><p className="event-date">17 October 2026 · 6:30 PM</p><div className="event-rule"/><p>No formal ceremony, just good food, great company, stories, laughter, and one last celebration before we begin married life.</p><p className="event-footer">Come for the love. Stay for the stories.</p></article><article className="event"><span className="event-index">02 · THE WEDDING</span><h3>Hong Kong</h3><p className="event-date">21 October 2026 · 10:30 AM</p><div className="event-rule"/><p>Together with our families, we joyfully invite you to witness the celebration of our marriage at <strong>Cotton Tree Drive, Central, Hong Kong.</strong></p><p className="event-footer">Reception to follow.</p><button className="text-link" onClick={calendar}>Add the wedding to your calendar <span>↗</span></button></article></div><p className="timezone-note">Each celebration’s time is local to its city.</p><figure className="teacup-keepsake"><img src="/images/teacup.webp" alt="Illustrated bride and groom sitting together in a teacup" width="627" height="627" loading="lazy" /></figure></section>
 <section id="story" className="story section-pad reveal"><div className="story-copy"><span className="eyebrow">04 / Our story, our map</span><h2>Different places.<br/><em>The same love.</em></h2><p>What started as a conversation between two people living on opposite sides of the world became the greatest adventure of our lives.</p><p>From Newcastle and Davao to Tanzania, India, Hungary, and beyond, we collected passport stamps, unforgettable memories, and every reason to believe that love knows no borders.</p><p>There were time zones to navigate and flights to catch. But through every mile, we always found our way back to each other.</p><p>Now, we’re celebrating not just where we’re going, but everything and everyone that brought us here.</p><span className="handwritten">Many places. One love.</span></div><figure className="journey-map"><a href="/images/journey.webp" target="_blank" rel="noreferrer" aria-label="Open our illustrated journey map in full size"><img src="/images/journey.webp" alt="Illustrated journey from Newcastle and Davao, through Tanzania, India, Hungary, London, Edinburgh, Portugal, Amsterdam and the proposal at Alnwick Castle, to our wedding in Hong Kong" width="1130" height="1394" loading="lazy"/></a></figure><div className="destination-line">{stops.map((s,i)=><span key={s}>{s}{i<stops.length-1&&<i aria-hidden="true"> · </i>}</span>)}</div></section>
 <Postcards/><footer className="footer reveal"><span className="eyebrow">Our next destination</span><h2>Forever, <em>with you.</em></h2><span className="footer-monogram">R & G</span><p>21 October 2026 · Hong Kong</p><a href="#main" className="text-link">Back to the beginning ↑</a><span className="footer-small">SEALED WITH LOVE. SENT WITH JOY.</span></footer></main></>
}
